### ISSUE TITLE
f11 & f12 no longer working

### ISSUE THREAD

**Issue by mbolo01** [tlk/beoplay-macos-remote-gui#27] opened 2020-09-24 17:22 UTC
Despite all conditions being met, f11 and f12 are no loger working, all the other fn keys are.
Nothing changed in my Mac configuration that I could think about, I checked in Mission control and these Fn are not used.
I ran again the terminal default commands
Any idea where I should look?

**Comment by tlk** [comment] 2020-09-24 18:17
Oops, yes - it should be fixed now ...    😇

**Comment by mbolo01** [comment] 2020-09-24 20:49
Yep, fixed now!

Question: why does it not work when the app menu is expanded?
i.e. While the app menu is expanded, I want to use a FNx, it fails. I understand that I can use the mouse for that, but I don't get why it should not work in this case?

**Comment by tlk** [comment] 2020-09-25 14:31
Great!

Yes, there is an issue with hotkeys when the menu is open. Unfortunately, I don't understand the root cause. Tracking it over in #28 

Closing this one for now :-)

**Closed by tlk** 2020-09-25 14:31 UTC
